# Filterbank config
filterbank:
  stft_n_filters: 512
  stft_kernel_size: 400
  stft_stride: 100
masknet:
  architecture: DCCRN-CL
data:
  task: sep_noisy
  train_dir: data/wav16k/max/train-100
  valid_dir: data/wav16k/max/dev
  sample_rate: 16000
  n_src: 2
  segment: 4
training:
  epochs: 200
  batch_size: 12
  num_workers: 24
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
